name: 'Helm Publisher'
description: 'A GitHub Action for publishing Helm charts with Github Pages'
author: 'Simone Rodigari'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  owner:
    description: "The GitHub user or org that owns this repository, defaults to `GITHUB_REPOSITORY`"
    required: false
  repository:
    description: "The GitHub repository name, defaults to `GITHUB_REPOSITORY`"
    required: false
  branch:
    description: "The branch to publish charts, defaults to `gh-pages`"
    required: false
  target_dir:
    description: "The target directory to store the charts, defaults to `.`"
    required: false
  commit_username:
    description: "The user name used for the commit user"
    required: false
    default: ${{ github.actor }} 
  commit_email:
    description: "The email used for the commit user"
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
    - ${{ inputs.target_dir }}
    - ${{ inputs.commit_username }}
    - ${{ inputs.commit_email }}