name: publish-chart
on: [push]
jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: ./
        with:
          owner: srodi
          repository: demo-gcp-helm
          branch: gh-pages
          target_dir: ""
          commit_username: SRodi
          commit_email: simone.rodigari@gmail.com
          app_version: 1.16.0
          chart_version: 0.1.0
          token: ${{ secrets.BOT_GITHUB_TOKEN }}